### ISSUE TITLE
invalid class “DimReduc” object

### ISSUE THREAD

**Issue by gjhuizing** [PMBio/MuDataSeurat#1]
Hi,

`ReadH5MU` was giving me the following error:

```
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: No columnames present in cell embeddings, setting to 'atacpca_1:50'
Error in validObject(.Object) : 
  invalid class “DimReduc” object: invalid object for slot "feature.loadings" in class "DimReduc": got class "NULL", should be or extend class "matrix"
In addition: Warning messages:
1: In missing_on_read("/var", "global variables metadata") :
  Missing on read: /var. Seurat does not support global variables metadata.
2: In missing_on_read("/varp", "pairwise annotation of variables") :
  Missing on read: /varp. Seurat does not support pairwise annotation of variables.
```

I managed to fix it by computing the PCA embeddings explicitly. Before that I was plotting UMAPs without explicitly computing PCA before.

Putting it here in case someone encounters the same error. Does the conversion to Seurat require PCA embeddings ? Or maybe it does when UMAP is present ?

Anyway thanks for this compatibility tool!

Best,

GJ

**Comment by gjhuizing** [comment]
Hum that doesn't seem to work, I get the same error! But I'm not very familiar with R so maybe I installed the patch in the wrong way? I forked the repo, applied the patch and did  `remotes::install_github("gjhuizing/MuDataSeurat")`.

**Comment by ilia-kats** [comment]
No, you seem to have done everything correctly. In that case, it would be really helpful if you could provide a sample .h5mu file.
