### ISSUE TITLE
The anndata package expects 'anndata', not 'AnnData' as encoding-type

### ISSUE THREAD

**Issue by vals** [PMBio/MuDataSeurat#15]
It seems this line is causing H5AD files saved with MuDataSeurat to not be read.

https://github.com/PMBio/MuDataSeurat/blob/9a66a48bf00ea0e6d90f33654a5dc952d2ffb755/R/WriteUtils.R#L29

Compare with the reading code here: https://github.com/scverse/anndata/blob/b118ba4bfb182a29509d7b07cb5966fb0297be5a/anndata/_io/h5ad.py#L222

Best,
/Valentine

**Comment by zqfang** [comment]
I had the same issue. use my fork here if you want to try: https://github.com/zqfang/MuDataSeurat

**Comment by ilia-kats** [comment]
This is fixed in master.
